spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.aw-central.com/auth/realms/awc-realm
          jwk-set-uri: https://keycloak.aw-central.com/auth/realms/awc-realm/protocol/openid-connect/certs
